### ISSUE TITLE
Unable to use it with `graphql-ws` 

### ISSUE THREAD

**Issue by VictorGaiva** [maartenvanvliet/subscriptions-transport-ws#50]
Apollo is phasing out the usage of `subscriptions-transport-ws` in favor of `graphql-ws`, as described [here](https://www.apollographql.com/docs/react/api/link/apollo-link-ws).

Migrating Apollo Client configuration with the current `subscriptions-transport-ws`'s documented configuration doesn't work out of the box, giving the following error:

![Screenshot from 2022-04-10 22-34-42](https://user-images.githubusercontent.com/13839490/162650782-7484e1df-3349-4633-a270-4f6d3a24c53f.png)

Changing
```
socket("/absinthe-ws", AbsintheSocket, websocket: [subprotocols: ["graphql-ws"]])
```
to
```
socket("/absinthe-ws", AbsintheSocket, websocket: [subprotocols: ["graphql-transport-ws"]])
```

Doesn't fix the issue, now throwing:

```
[error] Ranch listener MyApp.Endpoint.HTTP had connection process started with :cowboy_clear:start_link/4 at #PID<0.615.0> exit with reason: {%SubscriptionsTransportWS.Error{message: "Illegal `type` \"subscribe\" in OperationMessage"}, [{SubscriptionsTransportWS.OperationMessage, :from_map, 1, [file: 'lib/subscriptions_transport_ws/operation_message.ex', line: 64]}, {SubscriptionsTransportWS.Socket, :__in__, 2, [file: 'lib/subscriptions_transport_ws/socket.ex', line: 337]}, {Phoenix.Endpoint.Cowboy2Handler, :websocket_handle, 2, [file: 'lib/phoenix/endpoint/cowboy2_handler.ex', line: 145]}, {:cowboy_websocket, :handler_call, 6, [file: '/my_app/deps/cowboy/src/cowboy_websocket.erl', line: 528]}, {:cowboy_http, :loop, 1, [file: '/my_app/deps/cowboy/src/cowboy_http.erl', line: 257]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}
```

**Comment by maartenvanvliet** [comment]
To elaborate a bit, there's https://github.com/geometerio/absinthe_graphql_ws for absinthe support for graphql-ws. 

I guess ideally a library would be able to support both but for now I suggest to use the other absinthe_graphql_ws.

**Comment by VictorGaiva** [comment]
That's why I closed the issue, when I realized it :D
