### ISSUE TITLE
Type mismatch for @callback handle_info/2 in Phoenix.Socket.Transport behaviour.

### ISSUE THREAD

**Issue by dchohfi** [maartenvanvliet/subscriptions-transport-ws#6]
Hi, I'm getting this error when linting my module.

I saw that `SubscriptionsTransportWS.Socket` do `@behaviour Phoenix.Socket.Transport`, so don't know if my module is doing something wrong or the lint is complaining about some wrong type returning on func `handle_info/2`.

Don't know if mix resolved some different version of dependencies and contracts might be varying.

Thank you.

**Comment by maartenvanvliet** [comment]
Hi, could you show the code giving the error message? And the version of Phoenix you're using.

**Comment by dchohfi** [comment]
This is the error displayed by the dialyzer:

```elixir
ws_agent_socket.ex:3:callback_type_mismatch
Type mismatch for @callback handle_info/2 in Phoenix.Socket.Transport behaviour.

Expected type:
{:ok, _} | {:push, {atom(), _}, _} | {:stop, _, _}

Actual type:
{:reply, :ok, {:text, _}, atom() | %{:json_module => atom(), _ => _}}

________________________________________________________________________________
```
Deps:

- :absinthe_phoenix, "2.0.1"
- :phoenix, "1.5.7"

**Comment by dchohfi** [comment]
Might be here?

https://github.com/maartenvanvliet/subscriptions-transport-ws/blob/113d3282789706abd3dbc1cc60e3a8cb2d72e509/lib/subscriptions_transport_ws/socket.ex#L314

**Comment by maartenvanvliet** [comment]
Thx! Could you checkout this branch (https://github.com/maartenvanvliet/subscriptions-transport-ws/tree/issues/fix-return-type) to see if it fixes the error, and the socket still behaves correctly (esp. around keep alive)

**Comment by dchohfi** [comment]
Thank you @maartenvanvliet, lint is now happy.

Just out of curiosity, how dangerous would this be in production? Could socket connection/messages get lost because of this type mismatch?
Also, does the lib have unit tests to cover this part of implementation? I would be glad to add if not.

Thank you again, this lib is really helpful and works pretty good.

**Comment by maartenvanvliet** [comment]
Yes, this is a bug in the socket. It would not have worked for keep alive and multi-node setups. 

I'll add tests to cover this.

**Comment by maartenvanvliet** [comment]
Should also add a github action to run dialyzer.

**Comment by maartenvanvliet** [comment]
Fix is pushed https://github.com/maartenvanvliet/subscriptions-transport-ws/releases/tag/v1.0.1

**Comment by dchohfi** [comment]
that worked amazingly well @maartenvanvliet, thank you!
